SELECT COMPANY_CODE, MAX(FOUNDER), COUNT(DISTINCT LEAD_MANAGER_CODE), COUNT(DISTINCT SENIOR_MANAGER_CODE), COUNT(DISTINCT MANAGER_CODE), COUNT(DISTINCT EMPLOYEE_CODE)
FROM COMPANY C 
JOIN EMPLOYEE E
USING(COMPANY_CODE)
GROUP BY COMPANY_CODE
ORDER BY COMPANY_CODE;