SELECT H.HACKER_ID, MAX(H.NAME)
FROM HACKERS H
JOIN SUBMISSIONS S
USING(HACKER_ID)
JOIN CHALLENGES C
USING(CHALLENGE_ID)
JOIN DIFFICULTY D
USING(DIFFICULTY_LEVEL)
WHERE S.SCORE = D.SCORE
GROUP BY H.HACKER_ID
HAVING COUNT(H.HACKER_ID) >= 2
ORDER BY COUNT(H.HACKER_ID) DESC, H.HACKER_ID;